// AUTO-GENERATED FILE.
// This file is auto-generated by the Ballerina OpenAPI tool.

import ballerina/http;

listener http:Listener ep0 = new (9090);

service / on ep0 {
    # Delete a todo
    #
    # + return - returns can be any of following types
    # http:NoContent (Deleted)
    # http:NotFound (No todo with that id)
    resource function delete todos/[string todoId]() returns http:NoContent|ErrorNotFound {
        int? index = findTodoIndex(todoId);
        if index is () {
            return notFoundError(todoId);
        }
        removeTodoAt(index);
        return http:NO_CONTENT;
    }

    # List all todos
    #
    # + return - A page of todos
    resource function get todos(int 'limit = 20, int offset = 0) returns inline_response_200 {
        return listTodosPage('limit, offset);
    }

    # Add a new todo
    #
    # + return - returns can be any of following types
    # http:Created (The created todo)
    # http:BadRequest (The title is missing or empty)
    resource function post todos(@http:Payload NewTodo payload) returns Todo|ErrorBadRequest {
        if isBlankTitle(payload.title) {
            return blankTitleError();
        }
        return addTodo(payload.title);
    }

    # Change a todo's title and/or completed flag
    #
    # + return - returns can be any of following types
    # http:Ok (The updated todo)
    # http:BadRequest (The title is empty)
    # http:NotFound (No todo with that id)
    resource function put todos/[string todoId](@http:Payload UpdateTodo payload) returns Todo|ErrorBadRequest|ErrorNotFound {
        string? newTitle = payload?.title;
        if newTitle is string && isBlankTitle(newTitle) {
            return blankTitleError();
        }
        int? index = findTodoIndex(todoId);
        if index is () {
            return notFoundError(todoId);
        }
        return applyUpdate(index, payload);
    }
}

public type Todo record {
    string id;
    string title;
    boolean completed;
};

public type UpdateTodo record {
    string title?;
    boolean completed?;
};

public type NewTodo record {
    string title;
};

public type ErrorNotFound record {|
    *http:NotFound;
    Error body;
|};

public type inline_response_200 record {
    # total matching items
    int count;
    # relative URI of the next page
    string? next?;
    # relative URI of the previous page
    string? previous?;
    Todo[] data;
};

public type Error record {
    # HTTP or application error code
    int code;
    # short human-readable label
    string message;
    # detailed explanation
    string description?;
    # URI to documentation
    string moreInfo?;
};

public type ErrorBadRequest record {|
    *http:BadRequest;
    Error body;
|};
